env:
  FLUSH_INTERVAL: 1
  GRACE_INTERVAL: 30

service:
  flush: ${FLUSH_INTERVAL}
  grace: ${GRACE_INTERVAL}
  daemon: off

pipeline:
  inputs:
    - name: forward
      listen: 0.0.0.0
      port: 24224
      buffer_chunk_size: 10MB
      buffer_max_size: 50MB

  filters:
    - name: lua
      match: "docker.*"
      script: /fluent-bit/scripts/strip_container_name.lua
      call: strip_name

  outputs:
    - name: stdout
      match: "*"

    - name: loki
      match: "docker.*"
      host: loki
      port: 3100
      compress: gzip
      labels: job=fluentbit, container_name=$container_name, service_name=$service_name, docker_tag=$docker_tag
